apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitemap-generator
  labels:
    app: sitemap-generator
spec:
  replicas: 1
  template:
    metadata:
      name: sitemap-generator
      labels:
        app: sitemap-generator
    spec:
      containers:
        - name: sitemap-generator
          image: guillaumerose/sitemap-generator-server:v1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: sitemap-generator
---
apiVersion: v1
kind: Service
metadata:
  name: sitemap-generator
spec:
  selector:
    app: sitemap-generator
  ports:
    - port: 8080
  type: LoadBalancer
